#!/bin/sh
# Make sure everything boot=lite needs is inside the initramfs.
PREREQ=""
prereqs() { echo "$PREREQ"; }
case "$1" in prereqs) prereqs; exit 0 ;; esac
. /usr/share/initramfs-tools/hook-functions
manual_add_modules loop squashfs overlay isofs vfat nls_iso8859_1 nls_cp437 usb_storage uas
copy_exec /sbin/blkid /sbin
copy_exec /sbin/losetup /sbin
copy_exec /bin/udevadm /bin 2>/dev/null || true
